name: dayonemp
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.1.0
  google_fonts: ^2.1.0
  custom_splash: ^0.0.2
  flutter_statusbar_text_color: ^0.1.2
  google_nav_bar: ^5.0.5
  fancy_bottom_bar: ^0.0.1
  line_icons: ^2.0.1
  draggable_bottom_sheet: ^0.1.2
  font_awesome_flutter: ^9.1.0
  syncfusion_flutter_sliders: ^19.2.51
  rflutter_alert: ^2.0.4
  page_transition: ^2.0.1-nullsafety.0
  provider: ^5.0.0
  google_sign_in: ^5.0.7
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.5.0
  geolocator: ^7.4.0
  flutter_map: ^0.13.1
  location: ^4.3.0
  google_maps_flutter: ^2.0.6
  geoflutterfire: ^3.0.1
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

